FROM donluispanis/ubuntu

COPY . /usr/src/linux_build
WORKDIR /usr/src/linux_build

RUN make fire_lin DONT_USE_LINUX_PRECOMPILED_BINARIES=""
RUN make dottunnel_lin DONT_USE_LINUX_PRECOMPILED_BINARIES=""
RUN make rotozoom_lin DONT_USE_LINUX_PRECOMPILED_BINARIES=""
RUN make deformations_lin DONT_USE_LINUX_PRECOMPILED_BINARIES=""
RUN make plasma_lin DONT_USE_LINUX_PRECOMPILED_BINARIES=""
RUN make planes_lin DONT_USE_LINUX_PRECOMPILED_BINARIES=""
RUN make geometry_lin DONT_USE_LINUX_PRECOMPILED_BINARIES=""
RUN make finaldemo_lin DONT_USE_LINUX_PRECOMPILED_BINARIES=""