FROM trzeci/emscripten

COPY . /usr/src/Fire
WORKDIR /usr/src/Fire

RUN emmake make fire_wasm NDEBUG=true
RUN emmake make clean_main
RUN emmake make plasma_wasm NDEBUG=true

LABEL Name=fire Version=0.0.1