name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: openrndr/setup-opengl@v1
    - name: build_debug
      run: ./build_all_linux.sh
    - name: build_release
      run: ./build_all_linux_release.sh
