name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: install opengl
      run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: build_debug
      run: ./build_all_linux.sh
    - name: build_release
      run: ./build_all_linux_release.sh
