name: Linux Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Linux_Debug_Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build . --file Dockerfile.linux
