name: Web Assembly Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  WASM_Release_Build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build . --file Dockerfile.wasm
