name: Windows Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Windows_Debug_Build:
    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build . --file Dockerfile.windows
