name: Windows Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Windows_Release_Build:
    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: eine/setup-msys2@v0
      - name: Installing Dev Tools
        run: msys2do pacman --noconfirm -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain
      - name: Build Release
        run: msys2do ./build_all_release.sh
