name: Windows Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Windows_Debug_Build:
    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: eine/setup-msys2@v2
      - name: Installing Dev Tools
        run: msys2 pacman --noconfirm -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain
      - name: Build Debug
        run: msys2 ./build_all.sh
